/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restoran.GUI;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restoran.dao.DetailOrderDAO;
import restoran.dao.MenuDAO;
import restoran.dao.OrderDAO;
import restoran.model.DetailOrder;
import restoran.model.Order;

/**
 *
 * @author USER
 */
public class RiwayatOrder extends javax.swing.JFrame {

    /**
     * Creates new form ListOrder
     */
    public RiwayatOrder() {
        initComponents();
        loadOrders();
    }
    
    private void loadOrders() {
        OrderDAO orderDAO = new OrderDAO();
        List<Order> orders = orderDAO.getAllPaidOrders();
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID Order", "Tanggal", "Status", "Total Harga"}, 0);
        for (Order order : orders) {
            model.addRow(new Object[]{
                    order.getId(),
                    order.getTanggalOrder(),
                    order.getStatus(),
                    order.getTotalHarga()
            });
        }
        tblOrder.setModel(model);
        tblOrder.setDefaultEditor(Object.class, null);
    }

    private void loadOrderDetails(int orderId) {
        DetailOrderDAO detailOrderDAO = new DetailOrderDAO();
        MenuDAO menuDAO = new MenuDAO();  // Untuk mengambil nama menu berdasarkan ID
        List<DetailOrder> details = detailOrderDAO.getDetailsByOrderId(orderId);

        // Definisikan kolom yang akan ditampilkan pada tabel detail
        DefaultTableModel model = new DefaultTableModel(new String[]{"Nama Menu", "Jumlah", "Subtotal"}, 0);

        // Iterasi detail order dan ambil nama menu menggunakan ID menu
        for (DetailOrder detail : details) {
            String namaMenu = menuDAO.getMenuNameById(detail.getIdMenu());  // Ambil nama menu

            model.addRow(new Object[]{
                    namaMenu,  // Menampilkan nama menu
                    detail.getJumlah(),
                    detail.getSubtotal()
            });
        }

        tblDetailOrder.setModel(model);
        tblOrder.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetailOrder = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deleteOrder = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("RIWAYAT ORDER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 29, -1, -1));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Order", "Tanggal", "Status", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 124, 400, 275));

        tblDetailOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Jumlah", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDetailOrder);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 124, 400, 275));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("RIWAYAT ORDER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 92, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DETAIL ORDER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 92, -1, -1));

        deleteOrder.setText("Hapus");
        deleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrderActionPerformed(evt);
            }
        });
        getContentPane().add(deleteOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 417, -1, -1));

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 417, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/pexels-gdtography-277628-950241.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -110, 1180, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrderActionPerformed
        int selectedRow = tblOrder.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih order untuk dihapus!");
            return;
        }

        int orderId = Integer.parseInt(tblOrder.getValueAt(selectedRow, 0).toString());
        OrderDAO orderDAO = new OrderDAO();
        orderDAO.deleteOrder(orderId);

        JOptionPane.showMessageDialog(this, "Order berhasil dihapus!");
        loadOrders();
    }//GEN-LAST:event_deleteOrderActionPerformed

    private void tblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderMouseClicked
        int selectedRow = tblOrder.getSelectedRow();
        if (selectedRow != -1) {
            // Ambil ID order dari kolom pertama (index 0)
            int orderId = Integer.parseInt(tblOrder.getValueAt(selectedRow, 0).toString());

            // Tampilkan detail order di tabel detail
            loadOrderDetails(orderId);
        }
    }//GEN-LAST:event_tblOrderMouseClicked

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembali;
    private javax.swing.JTable tblDetailOrder;
    private javax.swing.JTable tblOrder;
    // End of variables declaration//GEN-END:variables
}
