/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restoran.GUI;

import java.util.List;
import javax.swing.JOptionPane;
import restoran.DAO.KategoriDAO;
import restoran.dao.MenuDAO;
import restoran.model.Kategori;
import restoran.model.Menu;

/**
 *
 * @author USER
 */
public class UpdateMenu extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMenu
     */
    
    private int idMenu = -1; // ID menu, -1 jika mode Tambah
    
    public UpdateMenu() {
        initComponents();
        loadKategori();
    }
    
    // Overload constructor untuk mode Edit
    public UpdateMenu(int idMenu, String namaMenu, String kategori, double harga) {
        this();
        this.idMenu = idMenu;
        txtNamaMenu.setText(namaMenu);
        comboBoxKategori.setSelectedItem(kategori);
        txtHarga.setText(String.valueOf(harga));
    }
    
    // Mengisi ComboBox Kategori
    private void loadKategori() {
        KategoriDAO kategoriDAO = new KategoriDAO();
        List<Kategori> kategoris = kategoriDAO.readAll();
        comboBoxKategori.removeAllItems();
        for (Kategori kategori : kategoris) {
            comboBoxKategori.addItem(kategori.getNamaKategori());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNamaMenu = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        comboBoxKategori = new javax.swing.JComboBox<>();
        ubah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("EDIT MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 20, -1, -1));

        jLabel2.setText("Nama Menu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 66, -1, -1));

        jLabel3.setText("Kategori");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 100, -1, -1));

        jLabel4.setText("Harga");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 134, -1, -1));
        getContentPane().add(txtNamaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 63, 230, -1));
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 131, 230, -1));

        getContentPane().add(comboBoxKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 97, 230, -1));

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 171, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/pexels-gdtography-277628-950241.jpg"))); // NOI18N
        jLabel5.setText("jLabel4");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-500, -290, 1240, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        String namaMenu = txtNamaMenu.getText();
        String namaKategori = (String) comboBoxKategori.getSelectedItem();
        double harga = Double.parseDouble(txtHarga.getText());

        // Ambil ID Kategori berdasarkan nama
        KategoriDAO kategoriDAO = new KategoriDAO();
        Kategori kategori = new Kategori();
        kategori.setNamaKategori(namaKategori);
        int idKategori = kategoriDAO.getIdByName(kategori);


        MenuDAO menuDAO = new MenuDAO();

        if (idMenu == -1) { // Mode Tambah
            Menu menu = new Menu(0, idKategori, namaMenu, harga);
            menuDAO.create(menu);
            JOptionPane.showMessageDialog(this, "Menu berhasil ditambahkan!");
        } else { // Mode Edit
            Menu menu = new Menu(idMenu, idKategori, namaMenu, harga);
            if (harga>0){
                menuDAO.update(menu);
                JOptionPane.showMessageDialog(this, "Menu berhasil diupdate!");    
            }else{
                JOptionPane.showMessageDialog(this, "Masukkan Harga yang valid","Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        this.dispose(); // Tutup form setelah simpan
    }//GEN-LAST:event_ubahActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaMenu;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
